
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        exclude: "tests"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: [ --maxkb=500 ]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: trailing-whitespace
        exclude_types: ["markdown"]
      - id: end-of-file-fixer
        exclude_types: ["markdown"]
      - id: check-docstring-first
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
        args: [ --allow-missing-credentials ]
      - id: detect-private-key
      - id: mixed-line-ending
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest --cov=bdi_api --cov-report=html --cov-fail-under=50
        language: system
        pass_filenames: false
        always_run: true
